services:
  client:
    build: ./client
    volumes:
      - client_node_modules:/usr/app/node_modules
      - ./client:/usr/app
    command: yarn dev
    ports:
      - 5173:5173
    depends_on:
      - service
  service:
    build: ./service
    tty: true
    volumes:
      - ./service:/usr/app
    command: yarn dev
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8080
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  client_node_modules: